config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/overview", to: "home#overview", as: "overview" 
  resources :users
  resources :events do
    resources :performance do
      resources :comments
    end
  end

  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :performance
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :performances
  has_many :performers

  mount_uploader :event_attachment, EventUploader

  validates :event_name, length: { in: 3..255 }
  validates_presence_of :event_name, :event_description
  
  accepts_nested_attributes_for :performers, reject_if: ->(attributes){ attributes['name'].blank? }, allow_destroy: true

end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :user
  belongs_to :event
  
  mount_uploader :attachment, PerformanceUploader
  
  validates :title, length: { in : 3..255 }
  valodates validates_presence_of :title, :description, :attachment
end

app/models/performer.rb
class Performer < ApplicationRecord
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :events
  has_many :performances
  has_many :comments

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  VALID_PHONE_REGEX=/\A[6-9][0-9]{9}\z/.freeze

  validates :name, length: { in: 3..50 }
  validates :email, format: { with: VALID_EMAIL_REGEX }, length: { in: 7..50 }
  validates :mobile, format: { with: VALID_PHONE_REGEX }, length: { is: 10 }
  validates_presence_of :name, :email, :mobile
  validates_presence_of :password, on: create
  validates_uniqueness_of :email, :mobile

  def self.generate_auth_token(column, user)
    user[column] = SecureRandom.urlsafe_base64
    user.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  before_action :set_cache_headers
  helper_method :current_user
  
  def current_user
    if cookies[:auth_token]
      @current_user ||= User.find_by_auth_token(cookies[:auth_token])
    else
      @current_user = nil
    end
  end  

  def check_user_is_admin
    redirect_to overview_path,  flash: { warning: "Only admin" } unless current_user.admin
  end

  def authenticate_user!
    return if current_user.present? 
    redirect_to root_path, flash: { danger: t("application.authentication_error") }
  end

  private
  
  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def edit
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :check_user_is_admin, only: [:create, :new, :edit, :update]
  before_action :set_event, only: [:edit, :show, :update]
  def index
    @events = Event.all
  end

  def show
    @performances = @event.performances.all.include(:user, :event)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event), flash: {success: "event added"}
    else
      render "new", flash: {danger: "Invalid data. ttry again"}
    end

  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event), flash: { success: "Event updated" }
    else
      render "edit", flash: { danger: "Event update failed" }
    end
  end



  private

  def event_params
    params.require(:event).permit(:event_name, :event_description, :publish_at, performer_attributes: Performer.attribute_names.map(&:to_sym).push(:_destroy))
  end


  def set_event
    @event = Event.find([:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.last(10)
  end

  def overview
  end
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :authenticate_user!, :check_user_is_admin, only: [:create, :destroy, :edit, :new, :update]
  before_action :set_performance, only: [:destroy, :edit, :show, :update]
  
  def create 
    @performance  = Parformance.new(paerformance_params)
    @performance.user_id = current_user.id
    @performance.event_id = @event.id

    if @parformance.save
      redirect_to event_performance_path(@performance), flash: { success: "Performance added" }
    else
      render "new"
    end
  end
  
  def destroy
    if @performance.destroy
      redirect_to request.referrer, flash: { success: "performance deleted" }
    else
      redirect_to request.referrer, flash: { danger: "something went wrong" }
    end
  end

  def edit
  end
  
  def new
    @performance = Performance.new
  end


  def show
    @comment = Comment.new
    @comment.performance_id = @performance.id
    @comments = @performance.comments.order("id DESC")
  end

  def update
    if @performance.update(performance_params)
      redirect_to event_performance_path(@performance), flash: {success: "performance updated" }
    else
      redirect_to event_performance_path(@performance), flash: {danger: "something went wrong" }
    end
  end

  private

  def paerformance_params
    params.require(:performance).permit(:title, :description, :attachment)
  end

  def set_performance
    @performance = Performance.find([:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  before_action :set_user, only: [:create]
  before_action :set_redirect_path, only: [:new]

  def create
    return redirect_to root_path, flash: { warning: "Already logged in." } if current_user.present?
    begin
      user = @user && @user.authenticate(params[:login][:password])
    rescue BCrypt::Errors::InvalidHash
      render "new", flash: { danger: "Sometyhing went Wrong" }
      return
    end
    
    if user
      User.generate_auth_token(:auth_token, @user)
      if params[:remember_me]
          login_with_remember_me(@user)
        else
          login(@user)
        end
      if @user.admin
        redirect_to overview_path, flash: { success: "Welcome #{@user.name}."}
      else
        redirect_to root_path, flash: { warning: "Welcome #{@user.name}." }
      end
    else
      render "new", flash: { danger: "Invalid credentials" }
    end
  end  
  
  def destroy
    logout
    redirect_to root_path, flash: { success: "Logout successfull" }
  end

  def new
    return redirect_to root_path, flash: { warning: "Already logged in" } if current_user.present?
  end  

  private
  
  def set_redirect_path
    session[:return_to] = request.referer
  end
  def set_user
    @user = User.find_by_email(params[:login][:email])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :show, :destroy]
  before_action :check_user_is_admin, only: [:destroy]
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = Uesr.new(user_params)
    if user.save
      login(@user)
      redirect_to root_path, flash: {success: "Welcome to music label"}
    else
      render "new"
    end
  end

  def edit
  end

  def update

  
  private

  def user_params
    params.require(:user).permit(:name, :email, :mobile, :password, :confirm_password)
  end

  def set_user
    @user = User.find([:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def link_to_add_performer(name,f,association,**args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: 'add-fields ' + args[:class], data: {id: id, fields: fields.delete("\n")})
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    cookies[:auth_token] = user.auth_token
  end

  def login_with_remember_me(user)
    cookies.parmanent[:auth_token] = user.auth_token
  end

  def logout
    cookies.delete
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true} do |form| %>
  <div class="page-wrapper">
    <div class="article-wrapper">
      <div class="card">
        <div class="card-body">
          <% if["edit"].include?(params[:action])%>
            <h1 class="title text-center"> UPDATE EVENT</h1>
          <% else %>
            <h1 class="title text-center"> CREATE EVENT</h1>
          <% end %>
          <br />
          <div class="form-group row">
            <%= form.label :event_name, for: "event name", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold"%>
            <div class="col-12 col-sm-9 col-md-9 col-lg-10">
              <%= form.text_field :event_name, for: "event name", class: "form-control", autofocus: true, placeholder: "Enter Event name", required: true %>
            </div>
          </div>
          
          <div class="form-group row">
            <%= form.label :event_description, for: "event description", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold"%>
            <div class="col-12 col-sm-9 col-md-9 col-lg-10">
              <%= form.text_area :event_description,for: "event description", rows: "15", cols: "150", class: "form-control description-field", autofocus: true, placeholder: "Enter description" %>
            </div>
          </div>
          <div class="form-group row">
            <%= form.label :event_attachment, for: "event picture", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold"%>
            <div class="col-12 col-sm-9 col-md-9 col-lg-10">
              <%= form.file_field :enemt_image, for: "article image", class: "form-control"%>
            </div>
          </div>

          <div class="performer-container">
            <h4 class="add-performer">Add Performer</h4>
            <%= link_to_add_performer("", form, :performers, class: "fa fa-plus float-right") %>
            <%= form.fields_for :performer do |builder| %>
              <%= render "events/performer", f: builder%>
            <% end %>
          </div>
          <div class="row">
            <div class="col-12 text-center">
              <% if["edit"].include?(params[:action])%>
                <%= form.submit "UPDATE", class:"btn btn-success btn-lg" %>
              <% else %>
                <%= form.submit "CREATE", class:"btn btn-primary btn-lg" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events/_performer.html.erb
<div class="performer">
  <div class="row">
    <div class="col-12 col-sm-11">
      <div class="form-group row">
        <%= f.label :name,"Performer Name", for: "name", class:"col-12 col-sm-4 col-md-2 col-form-label font-weight-bolder"%>
        <div class="col-12 col-sm-8 col-md-10">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter performer name", required: true %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :description,"Description", for: "name", class:"col-12 col-sm-4 col-md-2 col-form-label font-weight-bolder"%>
        <div class="col-12 col-sm-8 col-md-10">
          <%= f.text_area :description, class: "form-control", placeholder: "Enter Description", required:
              true %>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-1">
      <%= f.hidden_field :_destroy %>
      <%= link_to "", "#", class: "remove-field fa fa-minus-circle" %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<%= render "form"%>

app/views/events/index.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-10 col-lg-8 col-xl-7">
    <div class="row">
      <div class="col-6">
        <%= link_to "create event", new_event_path, class: "btn btn-primary"%>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-8 col-lg-7 col-xl-6">
        <% @events.each do |event| %>
          <div class="row">
            <div class="col-4">
              <%= image_tag event.attachment.url %>
            </div>
            <div class="col-8">
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= render "form" %>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/home/index.html.erb
<div class="row">
  <div class="col-12 col-md-8 col-lg-7 col-xl-6">
    <% @events.each do |event| %>
      <div class="row">
        <div class="col-4">
          <%= image_tag event.attachment.url %>
        </div>
        <div class="col-8">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/overview.html.erb
<h1>Home#overview</h1>
<p>Find me in app/views/home/overview.html.erb</p>

app/views/layouts/_alert.html.erb
<% flash.each do |key, value| %>
  <div id="notice_wrapper" class="alert alert-<%= key%> alert-dismissible hide show align-items-center", role="alert">
    <span class="notice-text"><%= value %></span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<p class="footer-text text-center bg-dark">Copyright &copy; musiclable.example, 2020. All rights are reserved</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Music Label</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href=<%= root_path %>>Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%= events_path %>>Events</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <% if current_user.present? %>
        <li class="nav-item active">
          <%= link_to "Logout", session_path(current_user), method: "delete", class: "btn btn-success" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign in", new_session_path,class: "btn btn-success"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign_up", new_user_path, class: "btn btn-primary" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicLabel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
    <header>
     <%= render "layouts/navbar" %>
     <%= render "layouts/alert" %>
    </header>
    <main id="main">
      <%= yield %>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/performances/_form.html.erb
<%= form_for [@event, @performance], html: { multipart: true} do |form| %>
  <div class="page-wrapper">
    <div class="article-wrapper">
      <div class="card">
        <div class="card-body">
          <% if["edit"].include?(params[:action])%>
            <h1 class="title text-center"> UPDATE PERFORMNACE</h1>
          <% else %>
            <h1 class="title text-center"> CREATE PERFORMANCE</h1>
          <% end %>
          <br />
          <div class="form-group row">
            <%= form.label :title, for: "event name", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold"%>
            <div class="col-12 col-sm-9 col-md-9 col-lg-10">
              <%= form.text_field :title, for: "performance title", class: "form-control", autofocus: true, placeholder: "Enter Event name", required: true %>
            </div>
          </div>
          
          <div class="form-group row">
            <%= form.label :description, for: "performance description", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold"%>
            <div class="col-12 col-sm-9 col-md-9 col-lg-10">
              <%= form.text_area :description,for: "event description", rows: "15", cols: "150", class: "form-control description-field", autofocus: true, placeholder: "Enter description" %>
            </div>
          </div>
          <div class="form-group row">
            <%= form.label :attachment, for: "event picture", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold"%>
            <div class="col-12 col-sm-9 col-md-9 col-lg-10">
              <%= form.file_field :enemt_image, for: "article image", class: "form-control"%>
            </div>
          </div>

          <div class="row">
            <div class="col-12 text-center">
              <% if["edit"].include?(params[:action])%>
                <%= form.submit "UPDATE", class:"btn btn-success btn-lg" %>
              <% else %>
                <%= form.submit "CREATE", class:"btn btn-primary btn-lg" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/performances/edit.html.erb
<%= render "form"%>

app/views/performances/new.html.erb
<%= render "form"%>

app/views/performances/show.html.erb
<h1>Performances#show</h1>
<p>Find me in app/views/performances/show.html.erb</p>

app/views/users/_form.html.erb
<div class="page-wrapper bg-dark">
  <%= form_for @user do |form| %>
    <div class="row align-items-center sign-up-row justify-content-center no-gutters">
    <div class="col-12 col-md-6 col-lg-5 col-xl-4 signup-img-col">
      <div class="white-box sign-up-box">
        <div class="image-box">
          <%= image_tag "sign_up.jpg", alt: "signup_image", class: "signup-img" %>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-7 col-xl-6">
      <div class="white-box sign-up-box">
        <% if["edit"].include?(params[:action])%>
          <h1 class="title text-center"> UPDATE USER</h1>
        <% else %>
          <h1 class="title text-center"> SIGN UP</h1>
        <% end %>
        <br />
        <% if @user.errors.any? %>
          <% @user.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
          <%end%>
        <%end%>
        <div class="form-group row">
          <%= form.label :name, for: "name", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold"%>
          <div class="col-12 col-sm-9 col-md-9 col-lg-10">
            <%= form.text_field :name,for: "name", class: "form-control", autofocus: true, autocomplete: "name", placeholder: "Enter name", required: true %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= form.label :email, for: "email", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold"%>
          <div class="col-12 col-sm-9 col-md-9 col-lg-10">
            <%= form.email_field :email,for: "email", class: "form-control", autofocus: true, autocomplete: "email", placeholder: "Enter Email ID", required: true %>
          </div>
        </div>
        <div class="form-group row">
          <%= form.label :mobile, for: "Mobile Number", class:"col-12 col-sm-3 col-md-3 col-lg-3 col-form-label font-weight-bold"%>
          <div class="col-12 col-sm-9 col-md-9 col-lg-9">
            <%= form.text_field :mobile, class: "form-control", placeholder: "Enter 10 digit mobile no", required: true %>  
          </div>
        </div>
        </div>
        <div class="form-group row">
          <%= form.label :password, for: "password", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold" %>
          <div class="col-12 col-sm-9 col-md-9 col-lg-10">
            <%= form.password_field :password, for: "password", class: "form-control", autocomplete: "current-password", placeholder: "Enter Password", required: true %>
          </div>
        </div>
        <div class="form-group row">
          <%= form.label :confirm_password, for: "password", class:"col-12 col-sm-3 col-md-3 col-lg-2 col-form-label font-weight-bold" %>
          <div class="col-12 col-sm-9 col-md-9 col-lg-10">
            <%= form.password_field :conform_password, for: "confirm_password", class: "form-control", autocomplete: "current-password", placeholder: "Repeat Password", required: true %>
          </div>
        </div>
        <br />
        <div class="row align-items-center">
          <div class="col-7 text-left">
            <% if ["new"].include?(params[:action]) && !current_user.present? %>
              <div class="col-12"><p class="reg-text text-left font-weight-bold">Already a member?</p></div>
              <div class="col-12"><%= link_to "SIGN IN", new_session_path, class: "btn btn-success btn-md font-weight-bold" %></div>
            <% end %>
          </div>
          <div class="col-5 text-right">
            <% if["edit"].include?(params[:action])%>
              <%= form.submit "UPDATE", class:"btn btn-success btn-lg font-weight-bold" %>
            <% else %>
              <%= form.submit "SIGN UP", class:"btn btn-primary btn-lg font-weight-bold" %>
            <% end %>
          </div>
        </div>
      </div>
    </div> 
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>